In [1]:
import numpy as np

In [9]:
array = np.array([[12,23,2,13,12,31]],np.int64)


In [3]:
array[0,3]

13

In [4]:
array.shape

(1, 6)

In [10]:
array.dtype

dtype('int64')

In [13]:
array[0,1] =432

In [14]:
array

array([[ 12, 432,   2,  13,  12,  31]], dtype=int64)

In [18]:
rang = np.arange(70)

In [19]:
rang

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69])

In [24]:
arr =rang.reshape(5,14)

In [25]:
arr.shape


(5, 14)

In [27]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69])

In [28]:
hamza = [[1,2,3],[4,5,6],[7,8,9]]
print(type(hamza))

<class 'list'>


In [29]:
ary = np.array(hamza)
ary

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
ary.sum(axis=0)

array([12, 15, 18])

In [31]:
ary.sum(axis=1)

array([ 6, 15, 24])

In [32]:
ary.dtype

dtype('int32')

In [33]:
ary.shape

(3, 3)

In [34]:
ary

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
ary[2,1] = 65
ary

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [65, 65, 65]])

In [39]:
ary.ndim

2

In [40]:
np.where(ary>2)

(array([0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [41]:
ary

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [65, 65, 65]])

In [42]:
arr


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [43]:
np.where(arr>50)

(array([3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       dtype=int64),
 array([ 9, 10, 11, 12, 13,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
        12, 13], dtype=int64))

In [44]:
arr.revel

AttributeError: 'numpy.ndarray' object has no attribute 'revel'

In [45]:
arr.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69])

In [46]:
np.where(arr>50)

(array([3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       dtype=int64),
 array([ 9, 10, 11, 12, 13,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
        12, 13], dtype=int64))

In [47]:
ary

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [65, 65, 65]])

In [49]:
np.where(ary>=3)

(array([0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [56]:
b = np.arange(3*3*3).reshape(3,3,3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
