                                            Quator -2 UIT 
                                            uit91258(uit wifi passoward)
                                            
                                            (GOOGLE IT)
                                            
                                            POLA-RS 
                                            fider,pikle
                                            how to publish pip package
                                            pypi

In [2]:
import numpy as np

In [7]:
a = np.arange(27).reshape(3,3,3)
# a = np.arange(3*3*3).reshape(3,3,3)
print(a.ndim) # number of dimension/rank 3D
print(a.shape) # numbe fo axis in each dimension 
print(a.size) # number elements
a

3
(3, 3, 3)
27


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [6]:
a = np.arange(100).reshape(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [8]:
# 4 pictures resolution 8x8
a = np.arange(4*8*8).reshape(4,8,8)
a

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60,  61,  62,  63]],

       [[ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111],
        [112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127]],

       [[128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 15

# create numpy array

In [10]:
a = np.array([1,2,3],
            [4,5,6])

display(a)
print(a)
a[:,2:]

TypeError: Field elements must be 2- or 3-tuples, got '4'

 * np.array(),
*np.zeros()
np.ones()
np.empty
np.arrange()
np.linspace()


In [3]:
arr = np.array([2,1,3,5,6,78,7])
np.sort(arr)

array([ 1,  2,  3,  5,  6,  7, 78])

In [7]:
np.arange(5*3*3).reshape(-1,3,3)   # -1 sa auto dimension fill krty hai if agr hmy dimesion pta na ho

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]]])

# args

In [11]:
a = np.array([23,43,43,54,67,87,56,22])  # wo index btay ga jis ki value large hai
print(np.argmax(a))
print(np.argmin(a))
print(np.argsort(a))

5
7
[7 0 1 2 3 6 4 5]


# concentenation 

In [15]:
a = np.arange(1,11).reshape(5,2)
b = np.arange(11,21).reshape(5,2)
display(a)
display(b)


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [18]:
np.concatenate((a,b),axis=1)

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16],
       [ 7,  8, 17, 18],
       [ 9, 10, 19, 20]])

In [19]:
np.hstack((a,b))

array([[ 1,  2, 11, 12],
       [ 3,  4, 13, 14],
       [ 5,  6, 15, 16],
       [ 7,  8, 17, 18],
       [ 9, 10, 19, 20]])

In [20]:
np.vstack((a,b))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [21]:
np.stack((a,b))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [22]:
a = np.arange(2*2*2).reshape(2,2,2)
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [23]:
a.sum()

28

In [24]:
display(a)
a.sum(axis=1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

array([[ 2,  4],
       [10, 12]])

In [25]:
display(a)
a.sum(axis=0)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

array([[ 4,  6],
       [ 8, 10]])

In [26]:
display(a)
a.sum(axis=2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

array([[ 1,  5],
       [ 9, 13]])

#  Slicing , Indexing, Fancy Slicing

In [29]:
a=np.arange(4*4).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [30]:
print(a[0])


[0 1 2 3]


In [31]:
display(a)
display(a[::2])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [32]:
display(a)
display(a[[1,2,0,1]]) # apni marzi ka index da skty hai fancy slicing ma

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [ ]:
display(a)
display(a[[1,2,0,1]])

In [35]:
b = np.arange(1,8)
display(b)
b[b %2 ==0]

array([1, 2, 3, 4, 5, 6, 7])

array([2, 4, 6])

In [36]:
b = np.arange(1,8)
display(b)

array([1, 2, 3, 4, 5, 6, 7])

In [39]:
display(b)
b[(b %2 ==0) & (b %4 ==0)]

array([1, 2, 3, 4, 5, 6, 7])

array([4])

In [44]:
display(a)
display(np.split(a,2,axis=1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [45]:
np.vsplit(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [12]:
labels = ['cat','dog','apple','mango']
prediction =[78,65,77,78]
index = np.argmax(prediction)
print(labels[index])

cat


In [ ]:
enggQasim gitub